### GENERAL SETTINGS ###

# Site settings
title: UF AI
description: "The Artificial Intelligence Club At The University of Florida"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://ufai.xyz"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Archives page) is

colors:  #in hex code if not noted else
  primary: "#1ABC9C" #"#F70031"
  primary_rgb: "49,230,194" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  footer_links: "#1ABC9C"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/groups/UFAIClub/

# Club Contact Information
email: gatoraiclub@gmail.com

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mason Rawson
    position: President
    img: MRawson.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Rohit Malhotra
    position: Vice President
    img: RMalhotra.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Luis Fernandes
    position: Outreach Director
    img: LFern.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Christian Marin
    position: Technical Director
    img: CMarin.jpg
    social:
      - title: envelope
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Michael Ngo
    position: Operations Director
    img: MNgo.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Simple about for the footer
about: "The Artificial Intelligence Club at The University of Florida aims to promote all things involving artificial
 intelligence!"
